# Problem 2:
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def solve():

	x0 = 1
	x1 = 2
	mysum = 2
	while x1 < 4e6:
		xt = x1
		x1 = x0+x1
		x0 = xt
		if x1%2 == 0:
			mysum = mysum + x1

	return mysum